name = "do-proxy-todo-storage"
compatibility_date = "2022-11-29"
main = "src/index.ts"

[durable_objects]
bindings = [
  {name = "TODO", class_name = "Todo"},
]

[[migrations]]
tag = "v1"
new_classes = ["Todo"]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false
